/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Diagnostic message with location and severity info */
export interface Diagnostic {
  message: string
  severity: DiagnosticSeverity
  range: Range
  code?: string
  source?: string
  relatedInfo?: string
}

export interface DiagnosticList {
  items: Array<Diagnostic>
}

/** Diagnostic severity levels */
export declare const enum DiagnosticSeverity {
  Hint = 1,
  Info = 2,
  Warning = 4,
  Error = 8
}

/**
 * Format a parsed AST back to a query string (normalized form).
 * Returns None if the query cannot be parsed.
 */
export declare function format(query: string): string | null

/** Get statistics about a query without returning the full AST. */
export declare function getStats(query: string): QueryStats | null

/**
 * Check if a query string is valid (no syntax errors).
 * Returns true if the query can be parsed without errors.
 */
export declare function isValid(query: string): boolean

/**
 * Parse a tantivy query string.
 *
 * Returns a ParseOutput containing:
 * - `ok`: whether parsing succeeded without errors
 * - `ast`: the parsed AST as a JSON string
 * - `diagnostics`: array of diagnostic messages with positions
 * - `stats`: statistics about the query
 */
export declare function parse(query: string): ParseOutput

/** Result of parsing a query, exposed to JavaScript */
export interface ParseOutput {
  /** Whether parsing was successful (no errors) */
  ok: boolean
  /** The parsed AST as JSON (use JSON.parse() in JS to get the typed object) */
  ast?: string
  /** List of diagnostics */
  diagnostics: DiagnosticList
  /** Query statistics */
  stats?: QueryStats
}

/** A position in the source text (0-indexed) */
export interface Position {
  /** Line number (0-indexed) */
  line: number
  /** Column number (0-indexed) */
  column: number
  /** Byte offset in the source string */
  offset: number
}

/** Summary statistics about a parsed query */
export interface QueryStats {
  /** Total number of terms */
  termCount: number
  /** Maximum nesting depth */
  maxDepth: number
  /** Fields referenced in the query */
  fields: Array<string>
  /** Whether the query contains a match-all (*) */
  hasMatchAll: boolean
  /** Whether the query contains any boosted terms */
  hasBoost: boolean
  /** Whether the query contains any negations */
  hasNegation: boolean
  /** Whether the query contains any phrase queries */
  hasPhrase: boolean
  /** Whether the query contains any range queries */
  hasRange: boolean
}

export interface Range {
  /** Start position (inclusive) */
  start: Position
  /** End position (exclusive) */
  end: Position
}

/**
 * Transpile a tantivy query string to a Postgres tsquery expression tree.
 *
 * Parses and lints the query (same pipeline as `parse`), then emits a JSON
 * expression tree whose leaves are `{field, tsquery}` pairs. Each `tsquery`
 * string is meant to be passed as the second argument of
 * `to_tsquery(<config>, $1)` so lexeme normalization (stemming, casing,
 * stopwords) follows the target column's text-search configuration.
 *
 * Returns `ok: false` with diagnostics when the query cannot be parsed or
 * contains untranspilable constructs (wildcards, ranges, unknown fields).
 */
export declare function toTsquery(query: string, options?: TsqueryOptions | undefined | null): TsqueryOutput

/** Options for tsquery emission */
export interface TsqueryOptions {
  /** Field assigned to bare (unscoped) terms. Defaults to "content_exact". */
  defaultField?: string
  /** If provided, field-scoped terms referencing other fields produce an error. */
  allowedFields?: Array<string>
  /** Treat bare adjacent terms as AND (tantivy conjunction_mode). Defaults to true. */
  conjunctionMode?: boolean
  /** Maximum phrase slop expanded into `<N>` alternatives. Defaults to 5. */
  maxSlop?: number
}

/** Result of transpiling a query to tsquery form */
export interface TsqueryOutput {
  /** Whether transpilation succeeded (no error diagnostics) */
  ok: boolean
  /**
   * JSON expression tree (use JSON.parse() in JS). Nodes:
   * {"type":"match","field":string,"tsquery":string}
   * {"type":"and","children":[...]} | {"type":"or","children":[...]}
   * {"type":"not","child":{...}}
   * The `tsquery` string is intended for `to_tsquery(<config>, $1)`.
   */
  expression?: string
  /** Diagnostics from parsing, linting, and emission */
  diagnostics: DiagnosticList
}

/**
 * Validate a tantivy query string and return only diagnostics.
 * More efficient than `parse` when you only need to check validity.
 */
export declare function validate(query: string): DiagnosticList

/** Get the version of the parser library */
export declare function version(): string
