/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Diagnostic message with location and severity info */
export interface Diagnostic {
  message: string
  severity: DiagnosticSeverity
  range: Range
  /** Stable machine-readable rule id (e.g. `mixed-and-or`) */
  code?: string
  source?: string
  /** Longer explanation or a suggested fix */
  relatedInfo?: string
}

export interface DiagnosticList {
  items: Array<Diagnostic>
}

/** Diagnostic severity levels */
export declare const enum DiagnosticSeverity {
  Hint = 1,
  Info = 2,
  Warning = 4,
  Error = 8
}

/**
 * Rewrite a query in canonical form: explicit AND/OR/NOT, original grouping.
 * Returns null when the query has errors.
 */
export declare function format(query: string, options?: TinqlOptions | undefined | null): string | null

/** Get statistics about a query without returning the full AST. */
export declare function getStats(query: string, options?: TinqlOptions | undefined | null): QueryStats | null

/** Check if a query string is valid (no error diagnostics). */
export declare function isValid(query: string, options?: TinqlOptions | undefined | null): boolean

/**
 * Parse and lint a boolean query.
 *
 * Runs the same pipeline as `toTinql`, so a query that parses here is
 * guaranteed to transpile.
 */
export declare function parse(query: string, options?: TinqlOptions | undefined | null): ParseOutput

/** Result of parsing a query, exposed to JavaScript */
export interface ParseOutput {
  /** Whether the query is valid (no error diagnostics) */
  ok: boolean
  /** The syntax tree as JSON (use JSON.parse() in JS); nodes carry byte spans */
  ast?: string
  /** Diagnostics from parsing, linting and emission checks, ordered by position */
  diagnostics: DiagnosticList
  /** Query statistics */
  stats?: QueryStats
}

/** A position in the source text (0-indexed) */
export interface Position {
  /** Line number (0-indexed) */
  line: number
  /** Column within the line in UTF-16 code units (0-indexed), as editors count it */
  column: number
  /** Byte offset in the UTF-8 source string */
  offset: number
}

/** Summary statistics about a parsed query */
export interface QueryStats {
  /** Number of terms and phrases */
  termCount: number
  /** Maximum nesting depth */
  maxDepth: number
  /** Whether the query contains a match-all (*) */
  hasMatchAll: boolean
  /** Whether the query contains any boosted terms */
  hasBoost: boolean
  /** Whether the query contains any negations */
  hasNegation: boolean
  /** Whether the query contains any phrase queries */
  hasPhrase: boolean
  /** Whether the query contains any wildcard terms */
  hasWildcard: boolean
  /** Whether the query contains any fuzzy terms */
  hasFuzzy: boolean
  /** Whether the query contains any NEAR/THEN proximity operators */
  hasProximity: boolean
}

export interface Range {
  /** Start position (inclusive) */
  start: Position
  /** End position (exclusive) */
  end: Position
}

/** Options for analysis and TINQL emission */
export interface TinqlOptions {
  /** Treat bare adjacent terms as AND (true, default) or OR (false). */
  conjunctionMode?: boolean
  /** Maximum phrase proximity `"a b"~N`. Defaults to 20. */
  maxSlop?: number
  /** Maximum fuzzy edit distance `term~N`. Defaults to 2. */
  maxFuzzyDistance?: number
}

/** Result of transpiling a query to TINQL */
export interface TinqlOutput {
  /** Whether transpilation succeeded (no error diagnostics) */
  ok: boolean
  /** The TINQL string for `content ==> $1`, present only when `ok` */
  tinql?: string
  /** Diagnostics from parsing, linting, and emission */
  diagnostics: DiagnosticList
}

/**
 * Transpile a boolean query to a TINQL string for `content ==> $1`.
 *
 * Parses and lints the query (same pipeline as `parse`), then emits one
 * TINQL string with explicit parentheses, `AND NOT` for negation and
 * `* AND NOT (…)` for negation-only queries. Returns `ok: false` with
 * diagnostics when the query has any error.
 */
export declare function toTinql(query: string, options?: TinqlOptions | undefined | null): TinqlOutput

/** Validate a boolean query and return only diagnostics. */
export declare function validate(query: string, options?: TinqlOptions | undefined | null): DiagnosticList

/** Get the version of the parser library */
export declare function version(): string
